"""Add StockMovement model

Revision ID: 42ef8477afae
Revises: 9b13ab9d003d
Create Date: 2025-04-11 16:29:07.694595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42ef8477afae'
down_revision = '9b13ab9d003d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citizen', schema=None) as batch_op:
        batch_op.drop_column('registered_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citizen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
