"""Add registered_by field to Citizen model

Revision ID: 9b13ab9d003d
Revises: da87cf191431
Create Date: 2025-04-11 15:11:09.303656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b13ab9d003d'
down_revision = 'da87cf191431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citizen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered_by', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['registered_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citizen', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('registered_by')

    # ### end Alembic commands ###
