"""Remove fields from citizen table

Revision ID: e70fadad4062
Revises: 2dba55759252
Create Date: 2025-04-11 14:39:24.493430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e70fadad4062'
down_revision = '2dba55759252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citizen', schema=None) as batch_op:
        batch_op.drop_column('allowed_seeds')
        batch_op.drop_column('allowed_fertilizer')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('logo_path',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('logo_path',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('citizen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_fertilizer', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('allowed_seeds', mysql.FLOAT(), nullable=False))

    # ### end Alembic commands ###
